notifications:
  email: false
language: node_js
node_js:
  - "7"
before_script:
  - npm install http-server
  - npm install jslint
script:
  - http-server&
  - NODE_SERVER_PID=$!
  - sleep 10
  - phantomjs specs.js
  - kill -9 $NODE_SERVER_PID
  - jslint main.js \
    scripts/preprocessor.js \
    scripts/cache.js \
    scripts/queryString.js \
    scripts/pushState.js \
    main.config.js \
    spec.config.js \
    spec/main.spec.js || true
