notifications:
  email: false
language: node_js
version:
  - "0.12"
before_script:
  - npm install -g http-server
  - npm install -g phantomjs
  - npm install -g jslint
script:
  - http-server&
  - NODE_SERVER_PID=$!
  - sleep 10
  - phantomjs specs.js
  - kill -9 $NODE_SERVER_PID
  - jslint '**/*.js' || true
