language: node_js
version:
  - "0.12"
before_script:
  - npm install -g phantomjs
  - npm install -g jslint
script:
  - phantomjs specs.js http://rkoeninger.github.io/spec.html
  - jslint '**/*.js' || true
