notifications:
  email: false
language: node_js
version:
  - "0.12"
before_script:
  - npm install http-server
  - npm install phantomjs-prebuilt@latest
  - npm install jslint
script:
  - http-server&
  - NODE_SERVER_PID=$!
  - sleep 20
  - ./node_modules/phantomjs-prebuilt/bin/phantomjs specs.js
  - kill -9 $NODE_SERVER_PID
  - jslint main.js main.config.js spec/main.spec.js spec.config.js || true
