notifications:
  email: false
language: node_js
version:
  - "5.1"
before_script:
  - npm install http-server
  - npm install jslint
script:
  - http-server&
  - NODE_SERVER_PID=$!
  - sleep 10
  - phantomjs specs.js
  - kill -9 $NODE_SERVER_PID
  - jslint main.js main.config.js spec/main.spec.js spec.config.js || true
